buyer/urls.py
from django.urls import path

from .views import *

app_name = 'buyer'

urlpatterns = [
    path('dashboard/', DashboardView.as_view(), name='buyer-dashboard'),
    path('generate-invoice/<int:order_id>', generate_invoice, name='generate-invoice'),
]

core/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt
from graphene_file_upload.django import FileUploadGraphQLView
from graphene_django.views import GraphQLView

from .views import *

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('category/<slug>/', CategoryView.as_view(), name='category'),
    path('product/<int:id>/', ProductDetailView.as_view(), name='product'),
    path('add-to-cart/<int:id>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<int:id>/', remove_from_cart, name='remove-from-cart'),
    path('remove-quantity-from-cart/<int:id>/', remove_quantity_from_cart, name='remove-quantity-from-cart'),
    path('shop/', ShopView.as_view(), name='shop'),
    path('cart/', CartListView.as_view(), name='cart'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),

    # graphql
    path("graphql", csrf_exempt(GraphQLView.as_view(graphiql=True))),
]

ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core')),
    # API
    path('v1/api/', include('core.api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

seller/urls.py
from django.urls import path

from .views import *

app_name = 'seller'

urlpatterns = [
    path('dashboard/', DashboardView.as_view(), name='seller-dashboard'),
    path('create-product/', ProductCreateView.as_view(), name='create-product'),
    path('edit-product/<int:id>/', ProductUpdateView.as_view(), name='edit-product'),
    path('update-shop/', ShopUpdateView.as_view(), name='update-shop')
]

templates/includes/sidebar.html
{% load static %}

<div class="col-sm-12 col-md-4 col-lg-3 page-sidebar">
    <aside>
        <div class="sidebar-box">
            <div class="user">
                <figure>
                    <a href="#">
                        <img class="img-fluid" src="{% static 'assets/img/avatar.png' %}" alt="">
                    </a>
                </figure>
                <div class="usercontent">
                    <h3>Hello {{ request.user.username }}!</h3>
                    <h4>User</h4>
                </div>
            </div>
            <nav class="navdashboard">
                <ul>
                    <li>
                        {% if request.user.user_type == 'seller' %}
                            <a href="{% url 'seller:seller-dashboard' %}">
                                <i class="lni-dashboard"></i>
                                <span>Dashboard</span>
                            </a>
                        {% else %}
                            <a href="{% url 'buyer:buyer-dashboard' %}">
                                <i class="lni-dashboard"></i>
                                <span>Dashboard</span>
                            </a>
                        {% endif %}
                    </li>
                    {% if request.user.user_type == 'seller' %}
                        <li>
                            <a href="{% url 'seller:create-product' %}">
                                <i class="lni-cog"></i>
                                <span>Create Product</span>
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'seller:update-shop' %}">
                                <i class="lni-cog"></i>
                                <span>Shop Settings</span>
                            </a>
                        </li>
                    {% endif %}
                    <li>
                        <a href="{% url 'account_logout' %}">
                            <i class="lni-enter"></i>
                            <span>Logout</span>
                        </a>
                    </li>
                </ul>
            </nav>
        </div>
    </aside>
</div>